package vista;

import controlador.Reportes;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

public class FrmMenu extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPane_menu;

    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension(1280, 720));
        
        this.setResizable(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/img/ICONOO.png")).getImage());
        this.setLocationRelativeTo(null);
        this.setTitle("MUCHA MURGA");
        
        jDesktopPane_menu = new JDesktopPane();


        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        jDesktopPane_menu.setPreferredSize(new Dimension(screenSize.width, screenSize.height - 110));
        this.add(jDesktopPane_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_NuevoUsuario = new javax.swing.JMenuItem();
        jMenuItem_GestionarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_AgregarProducto = new javax.swing.JMenuItem();
        jMenuItem_GestionarProducto = new javax.swing.JMenuItem();
        jMenuItem_ActualizarStock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_NuevoCliente = new javax.swing.JMenuItem();
        jMenuItem_GestionarClientes = new javax.swing.JMenuItem();
        Categoria = new javax.swing.JMenu();
        jMenuItem_NuevaCategoria = new javax.swing.JMenuItem();
        jMenuItem_GestionarCategorias = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_NuevaVenta = new javax.swing.JMenuItem();
        jMenuItem_GestionarVentas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_ReportesClientes = new javax.swing.JMenuItem();
        jMenuItem_ReportesCategorias = new javax.swing.JMenuItem();
        jMenuItem_ReportesProductos = new javax.swing.JMenuItem();
        jMenuItem_ReportesVentas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_Historial = new javax.swing.JMenuItem();
        jMenu_CerrarSesion = new javax.swing.JMenu();
        jMenuItem_CerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(66, 169, 174));
        setFocusTraversalPolicyProvider(true);
        setMaximumSize(new java.awt.Dimension(1280, 720));

        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setAlignmentX(0.0F);
        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setInheritsPopupMenu(true);
        jMenuBar1.setOpaque(true);

        jMenu1.setBackground(new java.awt.Color(66, 169, 174));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-usuario (1).png"))); // NOI18N
        jMenu1.setText("Usuarios");
        jMenu1.setAlignmentX(0.0F);
        jMenu1.setAlignmentY(0.0F);
        jMenu1.setBorderPainted(false);
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu1.setIconTextGap(15);
        jMenu1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenu1.setMinimumSize(new java.awt.Dimension(156, 55));
        jMenu1.setOpaque(true);
        jMenu1.setPreferredSize(new java.awt.Dimension(163, 60));

        jMenuItem_NuevoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_NuevoUsuario.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_NuevoUsuario.setText("Nuevo Usuario");
        jMenuItem_NuevoUsuario.setAlignmentX(0.0F);
        jMenuItem_NuevoUsuario.setAlignmentY(0.0F);
        jMenuItem_NuevoUsuario.setBorderPainted(false);
        jMenuItem_NuevoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_NuevoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_NuevoUsuario.setIconTextGap(0);
        jMenuItem_NuevoUsuario.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_NuevoUsuario.setOpaque(true);
        jMenuItem_NuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_NuevoUsuario);

        jMenuItem_GestionarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_GestionarUsuario.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_GestionarUsuario.setText("Gestionar Usuario");
        jMenuItem_GestionarUsuario.setAlignmentX(0.0F);
        jMenuItem_GestionarUsuario.setAlignmentY(0.0F);
        jMenuItem_GestionarUsuario.setBorderPainted(false);
        jMenuItem_GestionarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_GestionarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_GestionarUsuario.setIconTextGap(0);
        jMenuItem_GestionarUsuario.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_GestionarUsuario.setOpaque(true);
        jMenuItem_GestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_GestionarUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(66, 169, 174));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comercio-electronico.png"))); // NOI18N
        jMenu2.setText("Productos  ");
        jMenu2.setAlignmentX(0.0F);
        jMenu2.setAlignmentY(0.0F);
        jMenu2.setBorderPainted(false);
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu2.setIconTextGap(15);
        jMenu2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenu2.setMinimumSize(new java.awt.Dimension(156, 55));
        jMenu2.setOpaque(true);
        jMenu2.setPreferredSize(new java.awt.Dimension(163, 60));

        jMenuItem_AgregarProducto.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_AgregarProducto.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_AgregarProducto.setText("Agregar Producto");
        jMenuItem_AgregarProducto.setAlignmentX(0.0F);
        jMenuItem_AgregarProducto.setAlignmentY(0.0F);
        jMenuItem_AgregarProducto.setHideActionText(true);
        jMenuItem_AgregarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_AgregarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_AgregarProducto.setIconTextGap(0);
        jMenuItem_AgregarProducto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_AgregarProducto.setOpaque(true);
        jMenuItem_AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AgregarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_AgregarProducto);

        jMenuItem_GestionarProducto.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_GestionarProducto.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_GestionarProducto.setText("Gestionar Producto");
        jMenuItem_GestionarProducto.setAlignmentX(0.0F);
        jMenuItem_GestionarProducto.setAlignmentY(0.0F);
        jMenuItem_GestionarProducto.setHideActionText(true);
        jMenuItem_GestionarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_GestionarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_GestionarProducto.setIconTextGap(0);
        jMenuItem_GestionarProducto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_GestionarProducto.setOpaque(true);
        jMenuItem_GestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_GestionarProducto);

        jMenuItem_ActualizarStock.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_ActualizarStock.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_ActualizarStock.setText("Actualizar Stock");
        jMenuItem_ActualizarStock.setAlignmentX(0.0F);
        jMenuItem_ActualizarStock.setAlignmentY(0.0F);
        jMenuItem_ActualizarStock.setHideActionText(true);
        jMenuItem_ActualizarStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_ActualizarStock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_ActualizarStock.setIconTextGap(0);
        jMenuItem_ActualizarStock.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_ActualizarStock.setOpaque(true);
        jMenuItem_ActualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ActualizarStockActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_ActualizarStock);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(66, 169, 174));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu3.setText("Clientes");
        jMenu3.setAlignmentX(0.0F);
        jMenu3.setAlignmentY(0.0F);
        jMenu3.setBorderPainted(false);
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu3.setIconTextGap(15);
        jMenu3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenu3.setMinimumSize(new java.awt.Dimension(156, 55));
        jMenu3.setOpaque(true);
        jMenu3.setPreferredSize(new java.awt.Dimension(163, 60));

        jMenuItem_NuevoCliente.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_NuevoCliente.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_NuevoCliente.setText("Nuevo Cliente");
        jMenuItem_NuevoCliente.setAlignmentX(0.0F);
        jMenuItem_NuevoCliente.setAlignmentY(0.0F);
        jMenuItem_NuevoCliente.setHideActionText(true);
        jMenuItem_NuevoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_NuevoCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_NuevoCliente.setIconTextGap(0);
        jMenuItem_NuevoCliente.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_NuevoCliente.setOpaque(true);
        jMenuItem_NuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevoClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_NuevoCliente);

        jMenuItem_GestionarClientes.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_GestionarClientes.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_GestionarClientes.setText("Gestionar Clientes");
        jMenuItem_GestionarClientes.setAlignmentX(0.0F);
        jMenuItem_GestionarClientes.setAlignmentY(0.0F);
        jMenuItem_GestionarClientes.setHideActionText(true);
        jMenuItem_GestionarClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_GestionarClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_GestionarClientes.setIconTextGap(0);
        jMenuItem_GestionarClientes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_GestionarClientes.setOpaque(true);
        jMenuItem_GestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionarClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_GestionarClientes);

        jMenuBar1.add(jMenu3);

        Categoria.setBackground(new java.awt.Color(66, 169, 174));
        Categoria.setForeground(new java.awt.Color(255, 255, 255));
        Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/opciones (1).png"))); // NOI18N
        Categoria.setText("Categorías");
        Categoria.setAlignmentX(0.0F);
        Categoria.setAlignmentY(0.0F);
        Categoria.setBorderPainted(false);
        Categoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Categoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Categoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Categoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Categoria.setIconTextGap(15);
        Categoria.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Categoria.setMinimumSize(new java.awt.Dimension(156, 55));
        Categoria.setOpaque(true);
        Categoria.setPreferredSize(new java.awt.Dimension(163, 60));

        jMenuItem_NuevaCategoria.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_NuevaCategoria.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_NuevaCategoria.setText("Nueva Categoria");
        jMenuItem_NuevaCategoria.setAlignmentX(0.0F);
        jMenuItem_NuevaCategoria.setAlignmentY(0.0F);
        jMenuItem_NuevaCategoria.setHideActionText(true);
        jMenuItem_NuevaCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_NuevaCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_NuevaCategoria.setIconTextGap(0);
        jMenuItem_NuevaCategoria.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_NuevaCategoria.setOpaque(true);
        jMenuItem_NuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevaCategoriaActionPerformed(evt);
            }
        });
        Categoria.add(jMenuItem_NuevaCategoria);

        jMenuItem_GestionarCategorias.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_GestionarCategorias.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_GestionarCategorias.setText("Gestionar Categorias");
        jMenuItem_GestionarCategorias.setAlignmentX(0.0F);
        jMenuItem_GestionarCategorias.setAlignmentY(0.0F);
        jMenuItem_GestionarCategorias.setHideActionText(true);
        jMenuItem_GestionarCategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_GestionarCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_GestionarCategorias.setIconTextGap(0);
        jMenuItem_GestionarCategorias.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_GestionarCategorias.setOpaque(true);
        jMenuItem_GestionarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionarCategoriasActionPerformed(evt);
            }
        });
        Categoria.add(jMenuItem_GestionarCategorias);

        jMenuBar1.add(Categoria);

        jMenu4.setBackground(new java.awt.Color(66, 169, 174));
        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comercio (1).png"))); // NOI18N
        jMenu4.setText("Facturar");
        jMenu4.setAlignmentX(0.0F);
        jMenu4.setAlignmentY(0.0F);
        jMenu4.setBorderPainted(false);
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu4.setIconTextGap(15);
        jMenu4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenu4.setMinimumSize(new java.awt.Dimension(156, 55));
        jMenu4.setOpaque(true);
        jMenu4.setPreferredSize(new java.awt.Dimension(163, 60));

        jMenuItem_NuevaVenta.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_NuevaVenta.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_NuevaVenta.setText("Nueva Venta");
        jMenuItem_NuevaVenta.setAlignmentX(0.0F);
        jMenuItem_NuevaVenta.setAlignmentY(0.0F);
        jMenuItem_NuevaVenta.setHideActionText(true);
        jMenuItem_NuevaVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_NuevaVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_NuevaVenta.setIconTextGap(0);
        jMenuItem_NuevaVenta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_NuevaVenta.setOpaque(true);
        jMenuItem_NuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevaVentaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_NuevaVenta);

        jMenuItem_GestionarVentas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_GestionarVentas.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_GestionarVentas.setText("Gestionar Ventas");
        jMenuItem_GestionarVentas.setAlignmentX(0.0F);
        jMenuItem_GestionarVentas.setAlignmentY(0.0F);
        jMenuItem_GestionarVentas.setHideActionText(true);
        jMenuItem_GestionarVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_GestionarVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_GestionarVentas.setIconTextGap(0);
        jMenuItem_GestionarVentas.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_GestionarVentas.setOpaque(true);
        jMenuItem_GestionarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionarVentasActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_GestionarVentas);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(66, 169, 174));
        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jMenu5.setText("Reportes");
        jMenu5.setAlignmentX(0.0F);
        jMenu5.setAlignmentY(0.0F);
        jMenu5.setBorderPainted(false);
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu5.setIconTextGap(15);
        jMenu5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenu5.setMinimumSize(new java.awt.Dimension(156, 55));
        jMenu5.setOpaque(true);
        jMenu5.setPreferredSize(new java.awt.Dimension(163, 60));

        jMenuItem_ReportesClientes.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_ReportesClientes.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_ReportesClientes.setText("Reportes Clientes");
        jMenuItem_ReportesClientes.setAlignmentX(0.0F);
        jMenuItem_ReportesClientes.setAlignmentY(0.0F);
        jMenuItem_ReportesClientes.setHideActionText(true);
        jMenuItem_ReportesClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_ReportesClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_ReportesClientes.setIconTextGap(0);
        jMenuItem_ReportesClientes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_ReportesClientes.setOpaque(true);
        jMenuItem_ReportesClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ReportesClientesActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_ReportesClientes);

        jMenuItem_ReportesCategorias.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_ReportesCategorias.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_ReportesCategorias.setText("Reportes Categorías");
        jMenuItem_ReportesCategorias.setAlignmentX(0.0F);
        jMenuItem_ReportesCategorias.setAlignmentY(0.0F);
        jMenuItem_ReportesCategorias.setHideActionText(true);
        jMenuItem_ReportesCategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_ReportesCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_ReportesCategorias.setIconTextGap(0);
        jMenuItem_ReportesCategorias.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_ReportesCategorias.setOpaque(true);
        jMenuItem_ReportesCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ReportesCategoriasActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_ReportesCategorias);

        jMenuItem_ReportesProductos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_ReportesProductos.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_ReportesProductos.setText("Reportes Productos");
        jMenuItem_ReportesProductos.setAlignmentX(0.0F);
        jMenuItem_ReportesProductos.setAlignmentY(0.0F);
        jMenuItem_ReportesProductos.setHideActionText(true);
        jMenuItem_ReportesProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_ReportesProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_ReportesProductos.setIconTextGap(0);
        jMenuItem_ReportesProductos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_ReportesProductos.setOpaque(true);
        jMenuItem_ReportesProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ReportesProductosActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_ReportesProductos);

        jMenuItem_ReportesVentas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_ReportesVentas.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_ReportesVentas.setText("Reportes Ventas");
        jMenuItem_ReportesVentas.setAlignmentX(0.0F);
        jMenuItem_ReportesVentas.setAlignmentY(0.0F);
        jMenuItem_ReportesVentas.setHideActionText(true);
        jMenuItem_ReportesVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_ReportesVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_ReportesVentas.setIconTextGap(0);
        jMenuItem_ReportesVentas.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_ReportesVentas.setOpaque(true);
        jMenuItem_ReportesVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ReportesVentasActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_ReportesVentas);

        jMenuBar1.add(jMenu5);

        jMenu6.setBackground(new java.awt.Color(66, 169, 174));
        jMenu6.setForeground(new java.awt.Color(255, 255, 255));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte-de-ventas.png"))); // NOI18N
        jMenu6.setText("Historial");
        jMenu6.setAlignmentX(0.0F);
        jMenu6.setAlignmentY(0.0F);
        jMenu6.setBorderPainted(false);
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu6.setIconTextGap(15);
        jMenu6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenu6.setMinimumSize(new java.awt.Dimension(156, 55));
        jMenu6.setOpaque(true);
        jMenu6.setPreferredSize(new java.awt.Dimension(163, 60));

        jMenuItem_Historial.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_Historial.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_Historial.setText("Ver Historial");
        jMenuItem_Historial.setAlignmentX(0.0F);
        jMenuItem_Historial.setAlignmentY(0.0F);
        jMenuItem_Historial.setHideActionText(true);
        jMenuItem_Historial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_Historial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_Historial.setIconTextGap(0);
        jMenuItem_Historial.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_Historial.setOpaque(true);
        jMenuItem_Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_HistorialActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_Historial);

        jMenuBar1.add(jMenu6);

        jMenu_CerrarSesion.setBackground(new java.awt.Color(66, 169, 174));
        jMenu_CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_CerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu_CerrarSesion.setText("Cerrar Sesión");
        jMenu_CerrarSesion.setAlignmentX(0.0F);
        jMenu_CerrarSesion.setAlignmentY(0.0F);
        jMenu_CerrarSesion.setBorderPainted(false);
        jMenu_CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu_CerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu_CerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu_CerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu_CerrarSesion.setIconTextGap(5);
        jMenu_CerrarSesion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenu_CerrarSesion.setMinimumSize(new java.awt.Dimension(156, 55));
        jMenu_CerrarSesion.setOpaque(true);
        jMenu_CerrarSesion.setPreferredSize(new java.awt.Dimension(163, 60));

        jMenuItem_CerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem_CerrarSesion.setForeground(new java.awt.Color(33, 44, 62));
        jMenuItem_CerrarSesion.setText("Cerrar Sesion");
        jMenuItem_CerrarSesion.setAlignmentX(0.0F);
        jMenuItem_CerrarSesion.setAlignmentY(0.0F);
        jMenuItem_CerrarSesion.setHideActionText(true);
        jMenuItem_CerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuItem_CerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_CerrarSesion.setIconTextGap(0);
        jMenuItem_CerrarSesion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuItem_CerrarSesion.setOpaque(true);
        jMenuItem_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CerrarSesionActionPerformed(evt);
            }
        });
        jMenu_CerrarSesion.add(jMenuItem_CerrarSesion);

        jMenuBar1.add(jMenu_CerrarSesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_GestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionarProductoActionPerformed
        JInternalFrameGestionarProductos interGestProd = new JInternalFrameGestionarProductos();
        jDesktopPane_menu.add(interGestProd);
        interGestProd.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionarProductoActionPerformed

    private void jMenuItem_ReportesProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ReportesProductosActionPerformed
        Reportes reporte = new Reportes();
        reporte.reportesProductos();
    }//GEN-LAST:event_jMenuItem_ReportesProductosActionPerformed

    private void jMenuItem_NuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevaCategoriaActionPerformed
        JInternalFrameCategoria interCat = new JInternalFrameCategoria();
        jDesktopPane_menu.add(interCat);
        interCat.setVisible(true);
    }//GEN-LAST:event_jMenuItem_NuevaCategoriaActionPerformed

    private void jMenuItem_GestionarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionarCategoriasActionPerformed
        JInternalFrameGestionarCategoria interGestionarCat = new JInternalFrameGestionarCategoria();
        jDesktopPane_menu.add(interGestionarCat);
        interGestionarCat.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionarCategoriasActionPerformed

    private void jMenuItem_AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AgregarProductoActionPerformed
        JInternalFrameProductos interProd = new JInternalFrameProductos();
        jDesktopPane_menu.add(interProd);
        interProd.setVisible(true);
    }//GEN-LAST:event_jMenuItem_AgregarProductoActionPerformed

    private void jMenuItem_NuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevoClienteActionPerformed
        JInternalFrameClientes interCliente = new JInternalFrameClientes();
        jDesktopPane_menu.add(interCliente);
        interCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_NuevoClienteActionPerformed

    private void jMenuItem_GestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionarClientesActionPerformed
        JInternalFrameGestionarCliente interGestCliente = new JInternalFrameGestionarCliente();
        jDesktopPane_menu.add(interGestCliente);
        interGestCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionarClientesActionPerformed

    private void jMenuItem_ActualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ActualizarStockActionPerformed
        JInternalFrameActualizarStock interActualizar = new JInternalFrameActualizarStock();
        jDesktopPane_menu.add(interActualizar);
        interActualizar.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ActualizarStockActionPerformed

    private void jMenuItem_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CerrarSesionActionPerformed
        //System.exit(0);
        this.dispose();
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_CerrarSesionActionPerformed

    private void jMenuItem_NuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevoUsuarioActionPerformed
        JInternalFrameUsuario interUsuario = new JInternalFrameUsuario();
        jDesktopPane_menu.add(interUsuario);
        interUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem_NuevoUsuarioActionPerformed

    private void jMenuItem_GestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionarUsuarioActionPerformed
        JInternalFrameGestionarUsuario interGestUser = new JInternalFrameGestionarUsuario();
        jDesktopPane_menu.add(interGestUser);
        interGestUser.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionarUsuarioActionPerformed

    private void jMenuItem_NuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevaVentaActionPerformed
        JInternalFrameFacturar interFacturar = new JInternalFrameFacturar();
        jDesktopPane_menu.add(interFacturar);
        interFacturar.setVisible(true);
    }//GEN-LAST:event_jMenuItem_NuevaVentaActionPerformed

    private void jMenuItem_GestionarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionarVentasActionPerformed
        JInternalFrameGestionarVenta interGestVenta = new JInternalFrameGestionarVenta();
        jDesktopPane_menu.add(interGestVenta);
        interGestVenta.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionarVentasActionPerformed

    private void jMenuItem_ReportesClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ReportesClientesActionPerformed
        Reportes reporte = new Reportes();
        reporte.reportesClientes();
    }//GEN-LAST:event_jMenuItem_ReportesClientesActionPerformed

    private void jMenuItem_ReportesCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ReportesCategoriasActionPerformed
        Reportes reporte = new Reportes();
        reporte.reportesCategoria();
    }//GEN-LAST:event_jMenuItem_ReportesCategoriasActionPerformed

    private void jMenuItem_ReportesVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ReportesVentasActionPerformed
        Reportes reporte = new Reportes();
        reporte.reportesVentas();
    }//GEN-LAST:event_jMenuItem_ReportesVentasActionPerformed

    private void jMenuItem_HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_HistorialActionPerformed
        JInternalFrameGraficas interGrafica = new JInternalFrameGraficas();
        jDesktopPane_menu.add(interGrafica);
        interGrafica.setVisible(true);
    }//GEN-LAST:event_jMenuItem_HistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Categoria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_ActualizarStock;
    private javax.swing.JMenuItem jMenuItem_AgregarProducto;
    private javax.swing.JMenuItem jMenuItem_CerrarSesion;
    private javax.swing.JMenuItem jMenuItem_GestionarCategorias;
    private javax.swing.JMenuItem jMenuItem_GestionarClientes;
    private javax.swing.JMenuItem jMenuItem_GestionarProducto;
    private javax.swing.JMenuItem jMenuItem_GestionarUsuario;
    private javax.swing.JMenuItem jMenuItem_GestionarVentas;
    private javax.swing.JMenuItem jMenuItem_Historial;
    private javax.swing.JMenuItem jMenuItem_NuevaCategoria;
    private javax.swing.JMenuItem jMenuItem_NuevaVenta;
    private javax.swing.JMenuItem jMenuItem_NuevoCliente;
    private javax.swing.JMenuItem jMenuItem_NuevoUsuario;
    private javax.swing.JMenuItem jMenuItem_ReportesCategorias;
    private javax.swing.JMenuItem jMenuItem_ReportesClientes;
    private javax.swing.JMenuItem jMenuItem_ReportesProductos;
    private javax.swing.JMenuItem jMenuItem_ReportesVentas;
    private javax.swing.JMenu jMenu_CerrarSesion;
    // End of variables declaration//GEN-END:variables
}
