package vista;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Connection;
import conexion.Conexion;
import controlador.CtrlVenta;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import modelo.Venta;

public class JInternalFrameGestionarVenta extends javax.swing.JInternalFrame {

    private int idCliente = 0;
    private int idVenta;

    public JInternalFrameGestionarVenta() {
        initComponents();
        this.setSize(new Dimension(900, 500));

        this.cargarComboCliente();
        this.cargarTablaVentas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollCategoria = new javax.swing.JScrollPane();
        jTableVenta = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 3, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar Ventas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 890, 40));

        jPanel1.setBackground(new java.awt.Color(231, 231, 231));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableVenta.setBackground(new java.awt.Color(33, 44, 62));
        jTableVenta.setForeground(new java.awt.Color(255, 255, 255));
        jTableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollCategoria.setViewportView(jTableVenta);

        jPanel1.add(jScrollCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 710, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 730, 270));

        jPanel2.setBackground(new java.awt.Color(231, 231, 231));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new java.awt.Color(33, 44, 62));
        btnActualizar.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(234, 234, 234));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 130, 270));

        jPanel3.setBackground(new java.awt.Color(231, 231, 231));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 44, 62));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 20));

        txtFecha.setEnabled(false);
        jPanel3.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 150, 25));

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 44, 62));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cliente:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 50, 20));

        txtTotalPagar.setEnabled(false);
        jPanel3.add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 150, 25));

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 44, 62));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Total Pagar:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 20));

        jLabel7.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 44, 62));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Estado:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 70, 20));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel3.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 150, 25));

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione cliente:" }));
        jPanel3.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 150, 25));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 870, 80));

        jLabel2.setBackground(new java.awt.Color(33, 44, 62));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Venta venta = new Venta();
        CtrlVenta ctrlVenta = new CtrlVenta();
        String cliente, estado;
        cliente = cmbCliente.getSelectedItem().toString().trim();
        estado = cmbEstado.getSelectedItem().toString().trim();

        //obtenemos id cliente
        this.obtenerIdCliente(cliente);

        //Actualizamos los datos
        if (!cliente.equalsIgnoreCase("Seleccione cliente:")) {
            venta.setIdCliente(idCliente);

            if (estado.equalsIgnoreCase("Activo")) {
                venta.setEstado(1);
            } else {
                venta.setEstado(0);
            }

            if (ctrlVenta.actualizar(venta, idVenta)) {
                JOptionPane.showMessageDialog(null, "Venta actualizada");
                this.cargarTablaVentas();
                this.cargarComboCliente();
                this.limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar venta");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente para actualizar datos");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollCategoria;
    public static javax.swing.JTable jTableVenta;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables

// METODO PARA MOSTRAR TODOS LOS CLIENTES REGISTRADOS
    private void cargarTablaVentas() {
        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT v.idVenta AS id, "
                + "CONCAT(c.nombre, ' ', c.apellido) AS cliente, "
                + "v.valorPagar AS total, "
                + "v.fechaVenta AS fecha, "
                + "v.estado "
                + "FROM tb_venta AS v "
                + "JOIN tb_cliente AS c ON v.idCliente = c.idCliente;";

        model.addColumn("Nro");
        model.addColumn("Cliente");
        model.addColumn("Total Pagar");
        model.addColumn("Fecha Venta");
        model.addColumn("Estado");

        try (Connection con = Conexion.conectar(); Statement st = con.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                Object fila[] = new Object[5];
                for (int i = 0; i < 5; i++) {
                    if (i == 4) {
                        String estado = String.valueOf(rs.getObject(i + 1));
                        fila[i] = estado.equalsIgnoreCase("1") ? "Activo" : "Inactivo";
                    } else {
                        fila[i] = rs.getObject(i + 1);
                    }
                }
                model.addRow(fila);
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar la tabla: " + e.getMessage());
        }
        JInternalFrameGestionarVenta.jTableVenta = new JTable(model);
        JInternalFrameGestionarVenta.jScrollCategoria.setViewportView(JInternalFrameGestionarVenta.jTableVenta);

        jTableVenta.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int filaPoint = JInternalFrameGestionarVenta.jTableVenta.rowAtPoint(e.getPoint());
                int columnaPoint = 0;

                if (filaPoint > -1) {
                    idVenta = Integer.parseInt(model.getValueAt(filaPoint, columnaPoint).toString());
                    EnviarDatosVenta(idVenta);
                }
            }
        });
    }

    private void EnviarDatosVenta(int idVenta) {
        String sql = "SELECT v.idVenta, "
                + "v.idCliente, "
                + "CONCAT(c.nombre, ' ', c.apellido) AS cliente, "
                + "v.valorPagar AS total, "
                + "v.fechaVenta AS fecha, "
                + "v.estado "
                + "FROM tb_venta AS v "
                + "JOIN tb_cliente AS c ON v.idCliente = c.idCliente "
                + "WHERE v.idVenta = ?";

        try (Connection con = Conexion.conectar(); PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setInt(1, idVenta);

            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    cmbCliente.setSelectedItem(rs.getString("cliente"));
                    txtTotalPagar.setText(rs.getString("total"));
                    txtFecha.setText(rs.getString("fecha"));
                    int estado = rs.getInt("estado");
                    cmbEstado.setSelectedItem(estado == 1 ? "Activo" : "Inactivo");
                }
            }

        } catch (SQLException e) {
            System.out.println("Error al seleccionar la venta: " + e.getMessage());
        }
    }

    private void limpiar() {
        txtTotalPagar.setText("");
        txtFecha.setText("");
        cmbCliente.setSelectedItem("Seleccione cliente:");
        cmbEstado.setSelectedItem("Activo");
        idCliente = 0;
    }

    private void cargarComboCliente() {
        String sql = "select * from tb_cliente";

        try (Connection cn = Conexion.conectar(); Statement st = cn.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            cmbCliente.removeAllItems();
            cmbCliente.addItem("Seleccione cliente:");
            while (rs.next()) {
                cmbCliente.addItem(rs.getString("nombre") + " " + rs.getString("apellido"));
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar cliente: " + e);
        }
    }

    private void obtenerIdCliente(String cliente) {
        String sql = "SELECT idCliente FROM tb_cliente WHERE CONCAT(nombre, ' ', apellido) = ?";

        try (Connection cn = Conexion.conectar(); PreparedStatement pst = cn.prepareStatement(sql)) {

            pst.setString(1, cliente);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    idCliente = rs.getInt("idCliente");
                }
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar el id cliente: " + e);
        }
    }
}
