package vista;

import conexion.Conexion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author lolod
 */
public class JInternalFrameGraficarVentas extends javax.swing.JInternalFrame {

    ArrayList<Integer> listaCantidad = new ArrayList<>();
    ArrayList<String> listaFechas = new ArrayList<>();


    public JInternalFrameGraficarVentas() {
        initComponents();
        this.setSize(new Dimension(550, 650));

        this.almacenarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Swis721 BT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gráficas Ventas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 390, -1));

        jLabel1.setBackground(new java.awt.Color(33, 44, 62));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables


    //METODO PARA ALMACENAR EN LOS ARRAYLIST LOS DATOS A GRAFICAR
    private void almacenarDatos() {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select fechaVenta, count(fechaVenta) as Ventas from tb_venta "
                    + "where fechaVenta BETWEEN '" + JInternalFrameGraficas.fechaInicio + "' "
                    + "and '" + JInternalFrameGraficas.fechaFin + "' "
                    + "group by fechaVenta");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                listaFechas.add(rs.getString("fechaVenta"));
                listaCantidad.add(rs.getInt("Ventas"));
            }

        } catch (SQLException e) {
            System.out.println("Error en: " + e);
        }
    }

    //METODO PARA DETERMINAR CUAL ES EL DIA CON MAS VENTAS
    public int mayorVenta(ArrayList<Integer> listaCant) {
        int mayor = 0;
        for (int i = 0; i < listaCant.size(); i++) {
            if (listaCant.get(i) > mayor) {
                mayor = listaCant.get(i);
            }
        }

        return mayor;
    }

    //METODO PARA GRAFICAR LAS VENTAS
    @Override
    public void paint(Graphics g) {
        super.paint(g);

        int maxVenta = mayorVenta(listaCantidad);
        int largoNuevoIng = 0;
        int parametro1 = 133;
        int parametroFecha = 118;
        int parametro3 = 100;

        for (int i = 0; i < listaCantidad.size(); i++) {
            largoNuevoIng = listaCantidad.get(i) * 400 / maxVenta;

            switch (i) {
                case 0:
                    g.setColor(new Color(140, 0, 75)); //COLOR MORADO
                    break;
                case 1:
                    g.setColor(new Color(255, 0, 0)); //COLOR ROJO
                    break;
                case 2:
                    g.setColor(new Color(0, 0, 0)); //COLOR NEGRO
                    break;
                case 3:
                    g.setColor(new Color(255, 255, 255)); //COLOR BLANCO
                    break;
                case 4:
                    g.setColor(new Color(0, 85, 0)); //COLOR VERDE
                    break;
                default:
                    g.setColor(new Color(255, 127, 0)); //COLOR NARANJA
                    break;
            }

            g.fillRect(100, parametro3, largoNuevoIng, 40);
            g.drawString(listaFechas.get(i), 10, parametroFecha);
            g.drawString("Cantidad: " + listaCantidad.get(i), 10, parametro1);

            parametro1 += 50;
            parametroFecha += 50;
            parametro3 += 50;
        }
    }
}
