package vista;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Connection;
import conexion.Conexion;
import controlador.CtrlCliente;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import modelo.Cliente;

public class JInternalFrameGestionarCliente extends javax.swing.JInternalFrame {

    private int idCliente;

    public JInternalFrameGestionarCliente() {
        initComponents();
        this.setSize(new Dimension(900, 500));

        this.cargarTablaClientes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollCategoria = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar Clientes");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 890, 50));

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCliente.setBackground(new java.awt.Color(33, 44, 62));
        jTableCliente.setForeground(new java.awt.Color(255, 255, 255));
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollCategoria.setViewportView(jTableCliente);

        jPanel1.add(jScrollCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 710, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 730, 270));

        jPanel2.setBackground(new java.awt.Color(235, 235, 235));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new java.awt.Color(33, 44, 62));
        btnActualizar.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(33, 44, 62));
        btnEliminar.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 145, 100, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 130, 270));

        jPanel3.setBackground(new java.awt.Color(235, 235, 235));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 44, 62));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 20));
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 150, -1));

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 44, 62));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("DNI:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, 20));
        jPanel3.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 150, -1));
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 150, -1));

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 44, 62));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 20));

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 44, 62));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Teléfono:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 80, 20));
        jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 150, -1));

        jLabel7.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 44, 62));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Dirección:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 70, 20));
        jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 150, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 870, 80));

        jLabel2.setBackground(new java.awt.Color(33, 44, 62));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        if (!txtNombre.getText().isEmpty() && !txtApellido.getText().isEmpty() && !txtDNI.getText().isEmpty()) {
            //en caso de que los campos NO esten vacios
            Cliente cliente = new Cliente();
            CtrlCliente controlCliente = new CtrlCliente();
            cliente.setNombre(txtNombre.getText().trim());
            cliente.setApellido(txtApellido.getText().trim());
            cliente.setDni(txtDNI.getText().trim());
            cliente.setDireccion(txtDireccion.getText().trim());
            cliente.setTelefono(txtTelefono.getText().trim());

            if (controlCliente.actualizar(cliente, idCliente)) {
                //si el cliente se guarda
                JOptionPane.showMessageDialog(null, "CLIENTE ACTUALIZADO CORRECTAMENTE");
                this.cargarTablaClientes();
                this.limpiar();
            } else {
                //si hay error en el guardado
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR");
                this.limpiar();
            }

        } else {
            JOptionPane.showMessageDialog(null, "COMPLETE TODOS LOS CAMPOS");
            this.limpiar();
        }

        this.limpiar();
    }//GEN-LAST:event_btnActualizarActionPerformed


    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        CtrlCliente controlCliente = new CtrlCliente();
        if (idCliente == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente");
        } else {
            if (controlCliente.eliminar(idCliente)) {
                JOptionPane.showMessageDialog(null, "Cliente eliminado");
                this.cargarTablaClientes();
                this.limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "ERROR AL ELIMINAR CLIENTE");
                this.limpiar();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollCategoria;
    public static javax.swing.JTable jTableCliente;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    // METODO PARA MOSTRAR TODOS LOS CLIENTES REGISTRADOS
    private void cargarTablaClientes() {
        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT * from tb_cliente";

        try (Connection con = Conexion.conectar(); Statement st = con.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            model.addColumn("Nro");
            model.addColumn("Nombre");
            model.addColumn("Apellido");
            model.addColumn("DNI");
            model.addColumn("Direccion");
            model.addColumn("Telefono");
            model.addColumn("Estado");

            while (rs.next()) {
                Object fila[] = new Object[7];

                fila[0] = rs.getInt("idCliente");
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("apellido");
                fila[3] = rs.getString("dni");
                fila[4] = rs.getString("direccion");
                fila[5] = rs.getString("telefono");
                fila[6] = rs.getInt("estado");

                model.addRow(fila);
            }

            JInternalFrameGestionarCliente.jTableCliente = new JTable(model);
            JInternalFrameGestionarCliente.jScrollCategoria.setViewportView(JInternalFrameGestionarCliente.jTableCliente);

        } catch (SQLException e) {
            System.out.println("Error al cargar la tabla");
        }

        jTableCliente.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int filaPoint = JInternalFrameGestionarCliente.jTableCliente.rowAtPoint(e.getPoint());
                int columnaPoint = 0;

                if (filaPoint > -1) {
                    idCliente = Integer.parseInt(model.getValueAt(filaPoint, columnaPoint).toString());
                    EnviarDatosCliente(idCliente);
                }
            }
        });
    }
    
    //METODO PARRA ENVIAR LOS DATOS DEL CLIENTE SEGUN EL ID
    private void EnviarDatosCliente(int idCliente) {
        String sql = "select * from tb_cliente where idCliente = ?";

        try (Connection con = Conexion.conectar(); PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setInt(1, idCliente);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    txtNombre.setText(rs.getString("nombre"));
                    txtApellido.setText(rs.getString("apellido"));
                    txtDNI.setText(rs.getString("dni"));
                    txtDireccion.setText(rs.getString("direccion"));
                    txtTelefono.setText(rs.getString("telefono"));
                }
            }

        } catch (SQLException e) {
            System.out.println("Error al seleccionar el cliente: " + e.getMessage());
        }
    }

    private void limpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtDNI.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
    }

}
