package vista;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Connection;
import conexion.Conexion;
import controlador.CtrlProducto;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import modelo.Producto;

public class JInternalFrameGestionarProductos extends javax.swing.JInternalFrame {

    private int idProducto;
    int obtenerIdCategoriaCombo = 0;

    public JInternalFrameGestionarProductos() {
        initComponents();
        this.setSize(new Dimension(900, 500));

        this.cargarTablaProductos();
        this.cargarComboCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollCategoria = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbIva = new javax.swing.JComboBox<>();
        cmbCategorias = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 3, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestionar Productos");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 890, 60));

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollCategoria.setViewportView(jTableProductos);

        jPanel1.add(jScrollCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 710, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 730, 270));

        jPanel2.setBackground(new java.awt.Color(235, 235, 235));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new java.awt.Color(33, 44, 62));
        btnActualizar.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(225, 225, 225));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(33, 44, 62));
        btnEliminar.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(225, 225, 225));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 150, 100, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 130, 270));

        jPanel3.setBackground(new java.awt.Color(235, 235, 235));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 44, 62));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cantidad:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 20));

        txtCantidad.setEnabled(false);
        jPanel3.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 150, 25));

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 44, 62));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Precio:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, 20));
        jPanel3.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 110, 25));
        jPanel3.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 150, 25));

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 44, 62));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Descripción:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        cmbIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione IVA:", "No grava IVA", "10,5%", "21%" }));
        jPanel3.add(cmbIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 210, 25));

        cmbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoría:" }));
        jPanel3.add(cmbCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 210, 25));

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 44, 62));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("IVA:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 50, 20));

        jLabel7.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 44, 62));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Categoría:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 70, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 870, 80));

        jLabel2.setBackground(new java.awt.Color(33, 44, 62));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Producto producto = new Producto();
        CtrlProducto controlProducto = new CtrlProducto();
        String iva = "";
        String categoria = "";
        iva = cmbIva.getSelectedItem().toString().trim();
        categoria = cmbCategorias.getSelectedItem().toString().trim();

        // validar campos
        if (txtCantidad.getText().equals("") || txtPrecio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "COMPLETE TODOS LOS CAMPOS");

        } else {

            if (iva.equalsIgnoreCase("Seleccione IVA:")) {
                JOptionPane.showMessageDialog(null, "SELECCIONE EL IVA");
            } else {
                if (categoria.equalsIgnoreCase("Seleccione categoría:")) {
                    JOptionPane.showMessageDialog(null, "SELECCIONE LA CATEGORIA");
                } else {
                    try {
                        producto.setDescripcion(txtDescripcion.getText().trim());
                        int cantidad = Integer.parseInt(txtCantidad.getText().trim());

                        String precioTxt = txtPrecio.getText().trim();
                        double monto = 0.0;

                        if (precioTxt.contains(",")) {
                            precioTxt = precioTxt.replace(",", ".");
                        }

                        monto = Double.parseDouble(precioTxt); // Convertir a double

                        producto.setCantidad(cantidad);
                        producto.setPrecio(monto);

                        if (iva.equalsIgnoreCase("No grava IVA")) {
                            producto.setIva(0);
                        } else if (iva.equalsIgnoreCase("10,5%")) {
                            producto.setIva(10.5);
                        } else if (iva.equalsIgnoreCase("21%")) {
                            producto.setIva(21);
                        }

                        this.obtenerIdCategoria();
                        producto.setIdCategoria(obtenerIdCategoriaCombo);
                        producto.setEstado(1);

                        if (controlProducto.actualizar(producto, idProducto)) {
                            JOptionPane.showMessageDialog(null, "REGISTRO ACTUALIZADO");
                            this.limpiar();
                            this.cargarComboCategorias();
                            this.cargarTablaProductos();
                        } else {
                            JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR");
                        }

                    } catch (HeadlessException | NumberFormatException e) {
                        System.out.println("Error en: " + e);
                        JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR, CHEQUEE LOS FORMATOS INGRESADOS.");

                    }
                }
            }

        }
    }//GEN-LAST:event_btnActualizarActionPerformed


    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        CtrlProducto controlProducto = new CtrlProducto();
        if (idProducto == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        } else {
            if (controlProducto.eliminar(idProducto)) {
                JOptionPane.showMessageDialog(null, "Producto eliminado");
                this.cargarTablaProductos();
                this.cargarComboCategorias();
                this.limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "ERROR AL ELIMINAR PRODUCTO");
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbCategorias;
    private javax.swing.JComboBox<String> cmbIva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollCategoria;
    public static javax.swing.JTable jTableProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    //METODO PARA CARGAR COMBO BOX CATEGORIAS
    private void cargarComboCategorias() {
        String sql = "select * from tb_categoria";

        try (Connection cn = Conexion.conectar(); Statement st = cn.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            cmbCategorias.removeAllItems();
            cmbCategorias.addItem("Seleccione categoría:");

            while (rs.next()) {
                cmbCategorias.addItem(rs.getString("descripcion"));
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar categorias: " + e);
        }
    }

    // METODO PARA MOSTRAR TODOS LOS PRODUCTOS REGISTRADOS
    private void cargarTablaProductos() {
        String sql = "SELECT p.idProducto, p.descripcion, p.cantidad, p.precio, p.porcentajeIva, c.descripcion AS categoria, p.estado "
                + "FROM tb_producto p "
                + "INNER JOIN tb_categoria c ON p.idCategoria = c.IdCategoria";

        DefaultTableModel model = new DefaultTableModel();

        try (Connection con = Conexion.conectar(); Statement st = con.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            JInternalFrameGestionarProductos.jTableProductos = new JTable(model);
            JInternalFrameGestionarProductos.jScrollCategoria.setViewportView(JInternalFrameGestionarProductos.jTableProductos);

            model.addColumn("Nro");
            model.addColumn("Descripcion");
            model.addColumn("Cantidad");
            model.addColumn("Precio");
            model.addColumn("IVA");
            model.addColumn("Categoría");
            model.addColumn("Estado");

            while (rs.next()) {
                Object fila[] = new Object[7];

                fila[0] = rs.getInt("idProducto");
                fila[1] = rs.getString("descripcion");
                fila[2] = rs.getInt("cantidad");
                fila[3] = rs.getDouble("precio");
                fila[4] = rs.getDouble("porcentajeIva");
                fila[5] = rs.getString("categoria");
                fila[6] = rs.getInt("estado");

                model.addRow(fila);
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar la tabla: " + e);
        }

        jTableProductos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int filaPoint = JInternalFrameGestionarProductos.jTableProductos.rowAtPoint(e.getPoint());
                int columnaPoint = 0;

                if (filaPoint > -1) {
                    idProducto = Integer.parseInt(model.getValueAt(filaPoint, columnaPoint).toString());
                    EnviarDatosProducto(idProducto);
                }
            }
        });
    }

    //METODO PARA CALCULAR IVA
    double IVA = 0.0;

    private double calcularIva(double precio, double iva) {
        double pIva = iva;
        if (pIva == 0) {
            IVA = 0.0;
        } else if (pIva == 10.5) {
            IVA = precio * 0.105;
        } else if (pIva == 21) {
            IVA = precio * 0.21;
        }
        IVA = (double) Math.round(IVA * 100) / 100;
        return IVA;
    }

    //METODO PARA SETEAR COMBO BOX CON LOS DATOS DEL PRODUCTO
    private void EnviarDatosProducto(int idProducto) {
        String sql = "select * from tb_producto where idProducto = ?";

        try (Connection con = Conexion.conectar(); PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setInt(1, idProducto);

            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    txtDescripcion.setText(rs.getString("descripcion"));
                    txtCantidad.setText(rs.getString("cantidad"));
                    txtPrecio.setText(rs.getString("precio"));

                    double iva = rs.getDouble("porcentajeIva");

                    if (iva == 0) {
                        cmbIva.setSelectedItem("No grava IVA");
                    } else if (iva == 10.5) {
                        cmbIva.setSelectedItem("10,5%");
                    } else if (iva == 21) {
                        cmbIva.setSelectedItem("21%");
                    }

                    int idCate = rs.getInt("idCategoria");
                    cmbCategorias.setSelectedItem(relacionarCategorias(idCate));
                }
            }

        } catch (SQLException e) {
            System.out.println("Error al seleccionar el producto: " + e.getMessage());
        }
    }

    //METODO PARA DEVOLVER EL NOMBRE DE LA CATEGORIA SEGUN EL ID
    String descripcionCategoria = "";

    private String relacionarCategorias(int idCate) {
        String sql = "select descripcion from tb_categoria where idCategoria = ?";

        try (Connection cn = Conexion.conectar(); PreparedStatement pst = cn.prepareStatement(sql)) {

            pst.setInt(1, idCate);

            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    descripcionCategoria = rs.getString("descripcion");
                }
            }

        } catch (SQLException e) {
            System.out.println("Error al obtener la descripción de la categoría: " + e);
        }

        return descripcionCategoria;
    }

    //METODO PARA OBTENER ID CATEGORIA
    private int obtenerIdCategoria() {
        String sql = "select idCategoria from tb_categoria where descripcion = ?";

        try (Connection cn = Conexion.conectar(); PreparedStatement pst = cn.prepareStatement(sql)) {

            pst.setString(1, this.cmbCategorias.getSelectedItem().toString());

            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    obtenerIdCategoriaCombo = rs.getInt("idCategoria");
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL CONSULTAR ID CATEGORIA: " + e.getMessage());
        }

        return obtenerIdCategoriaCombo;
    }

    private void limpiar() {
        txtDescripcion.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        cmbCategorias.setSelectedItem("Seleccione categoría:");
        cmbIva.setSelectedItem("Seleccione IVA:");
    }

}
