package vista;

import controlador.CtrlCliente;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Cliente;

public class JInternalFrameClientes extends javax.swing.JInternalFrame {

    public JInternalFrameClientes() {
        initComponents();
        this.setSize(new Dimension(400, 300));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(231, 231, 231));
        btnAgregar.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(33, 44, 62));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 90, 30));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 210, 25));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 210, 25));
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 210, 25));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 210, 25));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 210, 25));

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nombre:");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 20));

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("DNI:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 20));

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 20));

        jLabel2.setFont(new java.awt.Font("Swis721 BT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nuevo Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 240, 40));

        jLabel9.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Dirección:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 20));

        jLabel10.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Teléfono:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 20));

        jLabel1.setBackground(new java.awt.Color(33, 44, 62));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Cliente cliente = new Cliente();
        CtrlCliente controlCliente = new CtrlCliente();

        if (!txtNombre.getText().isEmpty() && !txtApellido.getText().isEmpty() && !txtDNI.getText().isEmpty()) {
            //en caso de que los campos NO esten vacios
            if (!controlCliente.existeCliente(txtDNI.getText().trim())) {
                //valida que el cliente creado NO exista en la BD para poder continuar
                cliente.setNombre(txtNombre.getText().trim());
                cliente.setApellido(txtApellido.getText().trim());
                cliente.setDni(txtDNI.getText().trim());
                cliente.setDireccion(txtDireccion.getText().trim()); 
                cliente.setTelefono(txtTelefono.getText().trim()); 
                cliente.setEstado(1);
                
                if(controlCliente.guardar(cliente)){
                    //si el cliente se guarda
                    JOptionPane.showMessageDialog(null, "CLIENTE GUARDADO CORRECTAMENTE");
                    this.limpiar();
                } else {
                    //si hay error en el guardado
                    JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR");
                }
            } else {
                //en caso de que el cliente SI exista
                JOptionPane.showMessageDialog(null, "EL CLIENTE YA EXISTE");
            }

        } else {
            JOptionPane.showMessageDialog(null, "COMPLETE TODOS LOS CAMPOS");
        }
        
        this.limpiar();

    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    //METODO PARA LIMPIAR TXT
    private void limpiar() {
        txtApellido.setText("");
        txtNombre.setText("");
        txtDNI.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
    }
}
