package vista;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Connection;
import conexion.Conexion;
import controlador.CtrlUsuario;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import modelo.Usuario;

public class JInternalFrameGestionarUsuario extends javax.swing.JInternalFrame {

    private int idUsuario;

    public JInternalFrameGestionarUsuario() {
        initComponents();
        this.setSize(new Dimension(900, 500));

        this.cargarTablaUsuarios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollCategoria = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 44, 62));
        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar Usuarios");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 710, 50));

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollCategoria.setViewportView(jTableUsuario);

        jPanel1.add(jScrollCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 710, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 730, 270));

        jPanel2.setBackground(new java.awt.Color(232, 232, 232));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new java.awt.Color(33, 44, 62));
        btnActualizar.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setAlignmentY(0.0F);
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(33, 44, 62));
        btnEliminar.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 145, 100, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 130, 270));

        jPanel3.setBackground(new java.awt.Color(232, 232, 232));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 44, 62));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido:");
        jLabel3.setAlignmentY(0.0F);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 40, 80, 20));

        txtApellido.setAlignmentX(0.0F);
        txtApellido.setAlignmentY(0.0F);
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 150, 25));

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 44, 62));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Usuario:");
        jLabel4.setAlignmentY(0.0F);
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 80, 20));

        txtUsuario.setAlignmentX(0.0F);
        txtUsuario.setAlignmentY(0.0F);
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 150, 25));

        txtNombre.setAlignmentX(0.0F);
        txtNombre.setAlignmentY(0.0F);
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 150, 25));

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 44, 62));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre:");
        jLabel5.setAlignmentY(0.0F);
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 44, 62));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Teléfono:");
        jLabel6.setAlignmentY(0.0F);
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 80, 20));

        txtTelefono.setAlignmentX(0.0F);
        txtTelefono.setAlignmentY(0.0F);
        jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 150, 25));

        jLabel7.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 44, 62));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Contraseña:");
        jLabel7.setAlignmentY(0.0F);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 100, 20));

        txtPassword.setAlignmentX(0.0F);
        txtPassword.setAlignmentY(0.0F);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 150, 25));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 870, 80));

        jLabel2.setBackground(new java.awt.Color(33, 44, 62));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 890, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Usuario user = new Usuario();
        CtrlUsuario ctrlUser = new CtrlUsuario();

        if (idUsuario == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario");
        } else {
            if (!txtNombre.getText().isEmpty() && !txtApellido.getText().isEmpty() && !txtUsuario.getText().isEmpty() && !txtPassword.getText().isEmpty()
                    && !txtTelefono.getText().isEmpty()) {
                //en caso de que los campos NO esten vacios

                user.setNombre(txtNombre.getText().trim());
                user.setApellido(txtApellido.getText().trim());
                user.setUsuario(txtUsuario.getText().trim());
                user.setContraseña(txtPassword.getText().trim());
                user.setTelefono(txtTelefono.getText().trim());
                user.setEstado(1);

                if (ctrlUser.actualizar(user, idUsuario)) {
                    //si el cliente se guarda
                    JOptionPane.showMessageDialog(null, "USUARIO ACTUALIZADO CORRECTAMENTE");
                    this.cargarTablaUsuarios();
                    this.limpiar();
                } else {
                    //si hay error en el guardado
                    JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR");
                    this.limpiar();
                }

            } else {
                JOptionPane.showMessageDialog(null, "COMPLETE TODOS LOS CAMPOS");
                this.limpiar();
            }
        }

        this.limpiar();
    }//GEN-LAST:event_btnActualizarActionPerformed


    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        CtrlUsuario ctrlUser = new CtrlUsuario();
        if (idUsuario == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario");
        } else {
            if (ctrlUser.eliminar(idUsuario)) {
                JOptionPane.showMessageDialog(null, "Usuario eliminado");
                this.cargarTablaUsuarios();
                this.limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "ERROR AL ELIMINAR USUARIO");
                this.limpiar();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollCategoria;
    public static javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

// METODO PARA MOSTRAR TODOS LOS USUARIOS REGISTRADOS
    private void cargarTablaUsuarios() {
        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT * from tb_usuario";

        try (Connection con = Conexion.conectar(); Statement st = con.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            model.addColumn("Nro");
            model.addColumn("Nombre");
            model.addColumn("Apellido");
            model.addColumn("Usuario");
            model.addColumn("Contraseña");
            model.addColumn("Telefono");
            model.addColumn("Estado");

            while (rs.next()) {
                Object fila[] = new Object[7];

                fila[0] = rs.getInt("idUsuario");
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("apellido");
                fila[3] = rs.getString("usuario");
                fila[4] = rs.getString("password");
                fila[5] = rs.getString("telefono");
                fila[6] = rs.getInt("estado");

                model.addRow(fila);
            }

            JInternalFrameGestionarUsuario.jTableUsuario = new JTable(model);
            JInternalFrameGestionarUsuario.jScrollCategoria.setViewportView(JInternalFrameGestionarUsuario.jTableUsuario);

        } catch (SQLException e) {
            System.out.println("Error al cargar la tabla: " + e.getMessage());
        }

        jTableUsuario.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int filaPoint = JInternalFrameGestionarUsuario.jTableUsuario.rowAtPoint(e.getPoint());
                int columnaPoint = 0;

                if (filaPoint > -1) {
                    idUsuario = Integer.parseInt(model.getValueAt(filaPoint, columnaPoint).toString());
                    EnviarDatosUsuario(idUsuario);
                }
            }
        });
    }

    private void EnviarDatosUsuario(int idUsuario) {
        String sql = "select * from tb_usuario where idUsuario = ?";
        try (Connection con = Conexion.conectar(); PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setInt(1, idUsuario);

            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    txtNombre.setText(rs.getString("nombre"));
                    txtApellido.setText(rs.getString("apellido"));
                    txtUsuario.setText(rs.getString("usuario"));
                    txtPassword.setText(rs.getString("password"));
                    txtTelefono.setText(rs.getString("telefono"));
                }
            }

        } catch (SQLException e) {
            System.out.println("Error al seleccionar el usuario: " + e.getMessage());
        }
    }

    private void limpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtUsuario.setText("");
        txtPassword.setText("");
        txtTelefono.setText("");
    }

}
