package vista;

import conexion.Conexion;
import controlador.CtrlProducto;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import modelo.Producto;

/**
 *
 * @author lolod
 */
public class JInternalFrameActualizarStock extends javax.swing.JInternalFrame {

    //VARIABLES GLOBALES
    int idProducto = 0;
    int cantidad = 0;

    public JInternalFrameActualizarStock() {
        initComponents();

        setSize(new Dimension(400, 300));

        this.cargarComboProductos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActualizar = new javax.swing.JButton();
        cmbProducto = new javax.swing.JComboBox<>();
        txtStockActual = new javax.swing.JTextField();
        txtStockNuevo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblWallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new java.awt.Color(245, 245, 245));
        btnActualizar.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(33, 44, 62));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 100, 30));

        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione producto:" }));
        cmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 170, 25));

        txtStockActual.setEnabled(false);
        getContentPane().add(txtStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, 25));
        getContentPane().add(txtStockNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, 25));

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Stock Actual:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 20));

        jLabel3.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Producto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, 20));

        jLabel2.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Stock a Sumar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 20));

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actualizar Stock de Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 40));

        lblWallpaper.setBackground(new java.awt.Color(33, 44, 62));
        lblWallpaper.setOpaque(true);
        getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 390, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoActionPerformed
        Object selected = cmbProducto.getSelectedItem();
        if (selected != null && !selected.toString().equals("Seleccione producto:")) {
            mostrarStock();
        } else {
            txtStockActual.setText("");
            idProducto = 0;
            cantidad = 0;
        }
    }//GEN-LAST:event_cmbProductoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (!cmbProducto.getSelectedItem().equals("Seleccione producto:")) {

            if (!txtStockNuevo.getText().isEmpty()) {

                if (validar(txtStockNuevo.getText().trim())) {

                    if (Integer.parseInt(txtStockNuevo.getText()) > 0) {
                        Producto prod = new Producto();
                        CtrlProducto ctrlProd = new CtrlProducto();
                        int stockActual = Integer.parseInt(txtStockActual.getText().trim());
                        int stockNuevo = Integer.parseInt(txtStockNuevo.getText().trim());

                        stockNuevo = stockActual + stockNuevo;
                        prod.setCantidad(stockNuevo);

                        if (ctrlProd.actualizarStock(prod, idProducto)) {
                            JOptionPane.showMessageDialog(null, "STOCK ACTUALIZADO");
                            cmbProducto.setSelectedItem("Seleccione producto:");
                            txtStockActual.setText("");
                            txtStockNuevo.setText("");
                            this.cargarComboProductos();
                        } else {
                            JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "El valor no puede ser negativo o 0");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Indique un valor valido a sumar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Indique el stock a sumar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JTextField txtStockActual;
    private javax.swing.JTextField txtStockNuevo;
    // End of variables declaration//GEN-END:variables

    //METODO PARA CARGAR PRODUCTOS
    private void cargarComboProductos() {
        String sql = "SELECT * FROM tb_producto";

        try (Connection cn = Conexion.conectar(); Statement st = cn.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            cmbProducto.removeAllItems();
            cmbProducto.addItem("Seleccione producto:");

            while (rs.next()) {
                cmbProducto.addItem(rs.getString("descripcion"));
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar productos: " + e);
        }
    }

    //METODO PARA MOSTRAR EL STOCK
    private void mostrarStock() {
        String sql = "SELECT * FROM tb_producto WHERE descripcion = ?";

        try (Connection cn = Conexion.conectar(); PreparedStatement pst = cn.prepareStatement(sql)) {

            pst.setString(1, cmbProducto.getSelectedItem().toString());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                idProducto = rs.getInt("idProducto");
                cantidad = rs.getInt("cantidad");
                txtStockActual.setText(String.valueOf(cantidad));
            } else {
                txtStockActual.setText("");
            }

        } catch (SQLException e) {
            System.out.println("Error al mostrar stock: " + e);
        }
    }

    private boolean validar(String valor) {
        int num;
        try {
            num = Integer.parseInt(valor);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
}
