package vista;

import conexion.Conexion;
import controlador.CtrlVenta;
import controlador.VentaPDF;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DetalleVenta;
import modelo.Venta;

public class JInternalFrameFacturar extends javax.swing.JInternalFrame {

    //creamos el modelo de la tabla productos
    private DefaultTableModel modeloDatosProductos;

    //lista para el detalle de venta de los productos
    ArrayList<DetalleVenta> listaProductos = new ArrayList<>();
    private DetalleVenta producto;

    private int idCliente = 0;

    private int idProducto = 0;
    private String descripcion = "";
    private int cantidadProductosBDD = 0;
    private double precioUnitario = 0.0;
    private double porcentajeIva = 0.0;
    private int cantidad = 0;
    private double subtotal = 0.0;
    private double descuento = 0.0;
    private double iva = 0.0;
    private double totalPagar = 0.0;

    private int auxIdDetalle = 1;

    // variables para calculos globales
    private double subtotalGeneral = 0.0;
    private double descuentoGeneral = 0.0;
    private double ivaGeneral = 0.0;
    private double totalGeneral = 0.0;

    public JInternalFrameFacturar() {
        initComponents();
        this.setSize(new Dimension(800, 600));

        this.cargarComboCliente();
        this.cargarComboProductos();
        this.inicializarTablaProducto();
        this.listaTablaProductos();

        txtSubtotal.setText("0.00");
        txtIVA.setText("0.00");
        txtDescuento.setText("0.00");
        txtTotal.setText("0.00");
    }

    //metodo para inicializar la tabla de productos
    private void inicializarTablaProducto() {
        modeloDatosProductos = new DefaultTableModel();

        modeloDatosProductos.addColumn("N°");
        modeloDatosProductos.addColumn("Descripcion");
        modeloDatosProductos.addColumn("Cantidad");
        modeloDatosProductos.addColumn("P. Unitario");
        modeloDatosProductos.addColumn("Subtotal");
        modeloDatosProductos.addColumn("Descuento");
        modeloDatosProductos.addColumn("IVA");
        modeloDatosProductos.addColumn("Total Pagar");
        modeloDatosProductos.addColumn("Accion");

        this.jTableProductos.setModel(modeloDatosProductos);
    }

    // metodo para cargar la tabla de detalleVenta
    private void listaTablaProductos() {
        this.modeloDatosProductos.setRowCount(listaProductos.size());
        for (int i = 0; i < listaProductos.size(); i++) {
            this.modeloDatosProductos.setValueAt(i + 1, i, 0);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getDescripcion(), i, 1);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getCantidad(), i, 2);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getPrecioUnitario(), i, 3);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getSubtotal(), i, 4);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getDescuento(), i, 5);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getIva(), i, 6);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getTotalPagar(), i, 7);
            this.modeloDatosProductos.setValueAt("Eliminar", i, 8);

        }
        jTableProductos.setModel(modeloDatosProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        btnAnadir = new javax.swing.JButton();
        btnRegistrarVenta = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        cmbProducto = new javax.swing.JComboBox<>();
        cmbCliente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtIVA = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtEfectivo = new javax.swing.JTextField();
        txtCambio = new javax.swing.JTextField();
        btnCambio = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 44, 62));
        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 190));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 720, 210));

        btnAnadir.setText("Añadir Productos");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 160, 25));

        btnRegistrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 90, 70));

        btnBuscar.setText("Buscar por DNI");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 110, 25));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 50, 25));

        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione producto:" }));
        getContentPane().add(cmbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 150, 25));

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione cliente:" }));
        getContentPane().add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, 25));

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 90, 20));

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Producto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 20));

        jLabel3.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cliente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 20));

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 3, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Facturar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 780, 40));

        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(33, 44, 62));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Efectivo:");
        panel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 20));

        jLabel9.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 44, 62));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Total a pagar:");
        panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 20));

        jLabel8.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(33, 44, 62));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Cambio:");
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 20));

        jLabel7.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 44, 62));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Descuento:");
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 20));

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 44, 62));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Subtotal:");
        panel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        jLabel11.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(33, 44, 62));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("IVA:");
        panel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        txtSubtotal.setEnabled(false);
        panel2.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 130, 25));

        txtDescuento.setEnabled(false);
        panel2.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 130, 25));

        txtIVA.setEnabled(false);
        panel2.add(txtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 130, 25));

        txtTotal.setEnabled(false);
        panel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 130, 25));
        panel2.add(txtEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 130, 25));

        txtCambio.setEnabled(false);
        panel2.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, 25));

        btnCambio.setText("Cambio");
        btnCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioActionPerformed(evt);
            }
        });
        panel2.add(btnCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 133, 90, 50));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 370, 190));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 130, 25));

        jLabel2.setBackground(new java.awt.Color(33, 44, 62));
        jLabel2.setForeground(new java.awt.Color(33, 44, 62));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String clienteBuscar = txtBuscar.getText().trim();
        String sql = "SELECT nombre, apellido FROM tb_cliente WHERE dni = ?";

        try (Connection cn = Conexion.conectar(); PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setString(1, clienteBuscar);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    cmbCliente.setSelectedItem(rs.getString("nombre") + " " + rs.getString("apellido"));
                } else {
                    cmbCliente.setSelectedItem("Seleccione cliente:");
                    JOptionPane.showMessageDialog(null, "DNI INCORRECTO");
                }
            }

            txtBuscar.setText("");
        } catch (SQLException e) {
            System.out.println("Error al buscar el cliente: " + e);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        String combo = this.cmbProducto.getSelectedItem().toString();

        //validamos que seleccionen un prod
        if (combo.equalsIgnoreCase("Seleccione producto:")) {
            JOptionPane.showMessageDialog(null, "SELECCIONE UN PRODUCTO");
        } else {

            //validamos que ingrese una cantidad
            if (!txtCantidad.getText().isEmpty()) {

                //validamos que ingrese unicamente valores numericos
                if (esNumero(txtCantidad.getText().trim()) && Integer.parseInt(txtCantidad.getText()) > 0) {
                    cantidad = Integer.parseInt(txtCantidad.getText());
                    this.datosDelProducto();
                    //validar que la cantidad del producto no sea mayor a la de la BDD
                    if (cantidad <= cantidadProductosBDD) {

                        // calculamos y redondeamos a dos decimales
                        subtotal = precioUnitario * cantidad;
                        subtotal = (double) Math.round(subtotal * 100) / 100;

                        totalPagar = subtotal + iva + descuento;
                        iva = (double) Math.round(iva * 100) / 100;
                        descuento = (double) Math.round(descuento * 100) / 100;
                        totalPagar = (double) Math.round(totalPagar * 100) / 100;

                        // creamos el nuevo producto
                        producto = new DetalleVenta(auxIdDetalle, 1, idProducto, descripcion, cantidad, precioUnitario, subtotal, descuento, iva, totalPagar, "fecha", 1);
                        // añadimos a la lista

                        listaProductos.add(producto);
                        JOptionPane.showMessageDialog(null, "PRODUCTO AÑADIDO");
                        auxIdDetalle++;
                        txtCantidad.setText("");
                        this.cargarComboProductos();
                        this.calcularTotalPagar();

                    } else {
                        JOptionPane.showMessageDialog(null, "HA SOBREPASADO EL STOCK. El stock actual de " + descripcion + " es de: " + cantidadProductosBDD);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "SOLO SE ADMITEN DATOS NUMERICOS MAYORES A 0 EN CANTIDAD");
                }
            } else {
                JOptionPane.showMessageDialog(null, "INGRESA UNA CANTIDAD");
            }
        }
        this.listaTablaProductos();
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioActionPerformed
        if (!txtEfectivo.getText().isEmpty()) {
            if (esDouble(txtEfectivo.getText())) {
                double eft = Double.parseDouble(txtEfectivo.getText().trim());
                double totalPag = Double.parseDouble(txtTotal.getText().trim());

                if (eft >= totalPag) {
                    double cambio = eft - totalPag;
                    cambio = (double) Math.round(cambio * 100) / 100;
                    txtCambio.setText(String.valueOf(cambio));
                } else {
                    JOptionPane.showMessageDialog(null, "EL DINERO EN EFECTIVO NO ES SUFICIENTE");
                }
            } else {
                JOptionPane.showMessageDialog(null, "REVISE LOS VALORES INGRESADOS EN EFECTIVO");
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESA EL DINERO EN EFECTIVO");
        }
    }//GEN-LAST:event_btnCambioActionPerformed

    int idArrayList = 0;
    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        int filaPoint = jTableProductos.rowAtPoint(evt.getPoint());
        int columnaPoint = 0;

        if (filaPoint > -1) {
            idArrayList = (int) modeloDatosProductos.getValueAt(filaPoint, columnaPoint);
        }

        int opc = JOptionPane.showConfirmDialog(null, "¿Eliminar Producto?");
        //opciones del confirm dialog: si = 0, no = 1, cancel = 2, close = -1
        switch (opc) {
            case 0: // presiono si
                listaProductos.remove(idArrayList - 1);
                this.calcularTotalPagar();
                this.listaTablaProductos();
                break;
            case 1:
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jTableProductosMouseClicked

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        DetalleVenta detalleVenta = new DetalleVenta();
        Venta venta = new Venta();
        CtrlVenta ctrlVenta = new CtrlVenta();

        String fechaActual = "";
        Date date = new Date();
        fechaActual = new SimpleDateFormat("yyyy/MM/dd").format(date);

        if (!cmbCliente.getSelectedItem().equals("Seleccione cliente:")) {
            if (!listaProductos.isEmpty()) {

                this.obtenerIdCliente();
                //registrar venta
                venta.setIdVenta(0);
                venta.setIdCliente(idCliente);
                venta.setValorPagar(Double.parseDouble(txtTotal.getText()));
                venta.setFechaVenta(fechaActual);
                venta.setEstado(1);

                if (ctrlVenta.guardar(venta)) {
                    JOptionPane.showMessageDialog(null, "Venta guardada correctamente");
                    //generamos la factura de venta
                    VentaPDF pdf = new VentaPDF();
                    pdf.datosCliente(idCliente);
                    pdf.generarFacturaPDF();

                    for (DetalleVenta dv : listaProductos) {
                        detalleVenta.setIdDetalleVenta(0);
                        detalleVenta.setIdVenta(0);
                        detalleVenta.setIdProducto(dv.getIdProducto());
                        detalleVenta.setCantidad(dv.getCantidad());
                        detalleVenta.setPrecioUnitario(dv.getPrecioUnitario());
                        detalleVenta.setSubtotal(dv.getSubtotal());
                        detalleVenta.setDescuento(dv.getDescuento());
                        detalleVenta.setIva(dv.getIva());
                        detalleVenta.setTotalPagar(dv.getTotalPagar());
                        detalleVenta.setEstado(1);

                        if (ctrlVenta.guardarDetalle(detalleVenta)) {
                            System.out.println("Detalle de venta guardado correctamente");
                            auxIdDetalle = 1;
                            this.cargarComboCliente();
                            this.restarStockProductos(dv.getIdProducto(), dv.getCantidad());
                            txtSubtotal.setText("0.00");
                            txtIVA.setText("0.00");
                            txtDescuento.setText("0.00");
                            txtTotal.setText("0.00");
                        } else {
                            System.out.println("Error al guardar detalle de venta");
                        }

                    }
                    listaProductos.clear();
                    listaTablaProductos();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar venta");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe agregar al menos un producto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente");
        }
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambio;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableProductos;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtSubtotal;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    public static boolean esNumero(String texto) {
        return texto.matches("\\d+"); // Solo permite números enteros positivos
    }

    //VALIDAR QUE SEA DOUBLE
    public static boolean esDouble(String texto) {
        try {
            double num = Double.parseDouble(texto);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void cargarComboCliente() {
        String sql = "select * from tb_cliente";

        try (Connection cn = Conexion.conectar(); Statement st = cn.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            cmbCliente.removeAllItems();
            cmbCliente.addItem("Seleccione cliente:");
            while (rs.next()) {
                cmbCliente.addItem(rs.getString("nombre") + " " + rs.getString("apellido"));
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar cliente: " + e);
        }
    }

    private void cargarComboProductos() {
        String sql = "select * from tb_producto";

        try (Connection cn = Conexion.conectar(); Statement st = cn.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            cmbProducto.removeAllItems();
            cmbProducto.addItem("Seleccione producto:");
            while (rs.next()) {
                cmbProducto.addItem(rs.getString("descripcion"));
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar productos: " + e);
        }
    }

    private void datosDelProducto() {
        String sql = "SELECT * FROM tb_producto WHERE descripcion = ?";
        try (Connection cn = Conexion.conectar(); PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setString(1, String.valueOf(cmbProducto.getSelectedItem()));
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    idProducto = rs.getInt("idProducto");
                    descripcion = rs.getString("descripcion");
                    cantidadProductosBDD = rs.getInt("cantidad");
                    precioUnitario = rs.getDouble("precio");
                    porcentajeIva = rs.getDouble("porcentajeIva");

                    this.calcularIva(precioUnitario, porcentajeIva);
                }
            }

        } catch (SQLException e) {
            System.out.println("Error al obtener datos del producto: " + e.getMessage());
        }
    }

    private double calcularIva(double precioUnitario, double porcentajeIva) {
        if (porcentajeIva == 0) {
            iva = 0.0;
        } else if (porcentajeIva == 10.5) {
            iva = (precioUnitario * cantidad) * 0.105;
        } else if (porcentajeIva == 21) {
            iva = (precioUnitario * cantidad) * 0.21;
        }

        return iva;
    }

    private void calcularTotalPagar() {
        subtotalGeneral = 0;
        descuentoGeneral = 0;
        ivaGeneral = 0;
        totalGeneral = 0;

        for (DetalleVenta elemento : listaProductos) {
            subtotalGeneral += elemento.getSubtotal();
            descuentoGeneral += elemento.getDescuento();
            ivaGeneral += elemento.getIva();
            totalGeneral += elemento.getTotalPagar();

        }

        // redondeamos a dos decimales
        subtotalGeneral = (double) Math.round(subtotalGeneral * 100) / 100;
        ivaGeneral = (double) Math.round(ivaGeneral * 100) / 100;
        descuentoGeneral = (double) Math.round(descuentoGeneral * 100) / 100;
        totalGeneral = (double) Math.round(totalGeneral * 100) / 100;

        // enviamos datos a los txt
        txtSubtotal.setText(String.valueOf(subtotalGeneral));
        txtIVA.setText(String.valueOf(ivaGeneral));
        txtDescuento.setText(String.valueOf(descuentoGeneral));
        txtTotal.setText(String.valueOf(totalGeneral));
    }

    private void obtenerIdCliente() {
        String sql = "SELECT idCliente FROM tb_cliente WHERE CONCAT(nombre, ' ', apellido) = ?";
        try (Connection cn = Conexion.conectar(); PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setString(1, String.valueOf(cmbCliente.getSelectedItem()));
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    idCliente = rs.getInt("idCliente");
                }
            }

        } catch (SQLException e) {
            System.out.println("Error al obtener el id del cliente: " + e.getMessage());
        }
    }

    //METODO PARA RESTAR EL STOCK EN LA BD
    private void restarStockProductos(int idProducto, int cantidad) {
        String sqlSelect = "SELECT cantidad FROM tb_producto WHERE idProducto = ?";
        String sqlUpdate = "UPDATE tb_producto SET cantidad = ? WHERE idProducto = ?";

        try (Connection cn = Conexion.conectar(); PreparedStatement selectStmt = cn.prepareStatement(sqlSelect); PreparedStatement updateStmt = cn.prepareStatement(sqlUpdate)) {

            // Obtener el stock actual
            selectStmt.setInt(1, idProducto);
            ResultSet rs = selectStmt.executeQuery();

            if (rs.next()) {
                int stockActual = rs.getInt("cantidad");
                int nuevoStock = stockActual - cantidad;

                if (nuevoStock < 0) {
                    System.out.println("Error: Stock insuficiente para el producto ID " + idProducto);
                    return;
                }

                // Actualizar stock
                updateStmt.setInt(1, nuevoStock);
                updateStmt.setInt(2, idProducto);

                if (updateStmt.executeUpdate() > 0) {
                    System.out.println("Stock actualizado correctamente para producto ID " + idProducto);
                }
            } else {
                System.out.println("Producto con ID " + idProducto + " no encontrado.");
            }

        } catch (SQLException e) {
            System.out.println("Error al restar stock: " + e.getMessage());
        }
    }

}
