package vista;

import conexion.Conexion;
import java.awt.Dimension;
import conexion.Conexion;
import controlador.CtrlProducto;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import modelo.Producto;

public class JInternalFrameProductos extends javax.swing.JInternalFrame {

    int obtenerIdCategoriaCombo = 0;

    public JInternalFrameProductos() {
        initComponents();
        this.setSize(new Dimension(400, 300));

        this.cargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        cmbCategorias = new javax.swing.JComboBox<>();
        cmbIva = new javax.swing.JComboBox<>();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(33, 44, 62));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 30));

        cmbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoría:" }));
        getContentPane().add(cmbCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 210, 25));

        cmbIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione IVA:", "No grava IVA", "10,5%", "21%" }));
        getContentPane().add(cmbIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 210, 25));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 210, 25));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 210, 25));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 210, 25));

        jLabel8.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Categorias:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, 20));

        jLabel7.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("IVA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 20));

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Descripción:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 80, 20));

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 80, 20));

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 80, 20));

        jLabel2.setFont(new java.awt.Font("Swis721 BT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 390, 40));

        jLabel1.setBackground(new java.awt.Color(33, 44, 62));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Producto producto = new Producto();
        CtrlProducto controlProducto = new CtrlProducto();
        String iva = "";
        String categoria = "";
        iva = cmbIva.getSelectedItem().toString().trim();
        categoria = cmbCategorias.getSelectedItem().toString().trim();

        // validar campos vacíos
        if (txtDescripcion.getText().trim().isEmpty()
                || txtCantidad.getText().trim().isEmpty()
                || txtPrecio.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "COMPLETE TODOS LOS CAMPOS");

        } else if (!validarNumeros()) {
            // Se muestra el mensaje desde el método validarNumeros
            return;
        } else {
            if (!controlProducto.existeProducto(txtDescripcion.getText().trim())) {

                if (iva.equalsIgnoreCase("Seleccione IVA:")) {
                    JOptionPane.showMessageDialog(null, "SELECCIONE EL IVA");
                } else {
                    if (categoria.equalsIgnoreCase("Seleccione categoría:")) {
                        JOptionPane.showMessageDialog(null, "SELECCIONE LA CATEGORIA");
                    } else {
                        try {
                            producto.setDescripcion(txtDescripcion.getText().trim());
                            int cantidad = Integer.parseInt(txtCantidad.getText().trim());

                            String precioTxt = txtPrecio.getText().trim();
                            double monto = 0.0;

                            if (precioTxt.contains(",")) {
                                precioTxt = precioTxt.replace(",", ".");
                            }

                            monto = Double.parseDouble(precioTxt); // Convertir a double

                            producto.setCantidad(cantidad);
                            producto.setPrecio(monto);

                            if (iva.equalsIgnoreCase("No grava IVA")) {
                                producto.setIva(0);
                            } else if (iva.equalsIgnoreCase("10,5%")) {
                                producto.setIva(10.5);
                            } else if (iva.equalsIgnoreCase("21%")) {
                                producto.setIva(21);
                            }

                            this.obtenerIdCategoria();
                            producto.setIdCategoria(obtenerIdCategoriaCombo);
                            producto.setEstado(1);

                            if (controlProducto.guardar(producto)) {
                                JOptionPane.showMessageDialog(null, "REGISTRO GUARDADO");
                                this.limpiar();
                                this.cargarCategorias();
                            } else {
                                JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR");
                            }

                        } catch (HeadlessException | NumberFormatException e) {
                            System.out.println("Error en: " + e);
                        }
                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "EL PRODUCTO YA EXISTE EN LA BD");
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cmbCategorias;
    private javax.swing.JComboBox<String> cmbIva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    //METODO PARA LIMPIAR TXT
    private void limpiar() {
        txtCantidad.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");

    }

    //METODO PARA CARGAR COMBO BOX CATEGORIAS
    private void cargarCategorias() {
        cmbCategorias.removeAllItems();
        cmbCategorias.addItem("Seleccione categoría:");
        String sql = "SELECT * FROM tb_categoria";

        try (Connection cn = Conexion.conectar(); Statement st = cn.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                cmbCategorias.addItem(rs.getString("descripcion"));
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar categorias: " + e);
        }
    }

    //METODO PARA OBTENER ID CATEGORIA
    private int obtenerIdCategoria() {
        String sql = "SELECT idCategoria FROM tb_categoria WHERE descripcion = ?";

        try (Connection cn = Conexion.conectar(); PreparedStatement pst = cn.prepareStatement(sql)) {

            pst.setString(1, this.cmbCategorias.getSelectedItem().toString());
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    obtenerIdCategoriaCombo = rs.getInt("idCategoria");
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL CONSULTAR ID CATEGORIA: " + e.getMessage());
        }

        return obtenerIdCategoriaCombo;
    }

    // metodo auxiliar para validar numeros
    private boolean validarNumeros() {
        try {
            int cantidad = Integer.parseInt(txtCantidad.getText().trim());
            String precioTxt = txtPrecio.getText().trim();

            if (precioTxt.contains(",")) {
                precioTxt = precioTxt.replace(",", ".");
            }

            double precio = Double.parseDouble(precioTxt);

            if (cantidad < 0 || precio < 0) {
                JOptionPane.showMessageDialog(null, "Cantidad y precio deben ser positivos.");
                return false;
            }

            return true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad y un precio válidos.");
            return false;
        }
    }

}
