package vista;

import java.awt.Dimension;
import javax.swing.JTextField;
import static vista.FrmMenu.jDesktopPane_menu;

public class JInternalFrameGraficas extends javax.swing.JInternalFrame {

    public static String fechaInicio = "";
    public static String fechaFin = "";

    public JInternalFrameGraficas() {
        initComponents();
        this.setSize(new Dimension(450, 300));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dchFin = new com.toedter.calendar.JDateChooser();
        dchInicio = new com.toedter.calendar.JDateChooser();
        btnGraficar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dchFin.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dchFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 190, 25));

        dchInicio.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dchInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 190, 25));

        btnGraficar.setForeground(new java.awt.Color(255, 255, 255));
        btnGraficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte-de-ventas.png"))); // NOI18N
        btnGraficar.setBorder(null);
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGraficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 50, 40));

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Fecha inicio:");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 90, 20));

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha fin:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 90, 20));

        jLabel2.setFont(new java.awt.Font("Swis721 BT", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione fechas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 440, 40));

        jLabel1.setBackground(new java.awt.Color(33, 44, 62));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        fechaInicio = ((JTextField) dchInicio.getDateEditor().getUiComponent()).getText();
        fechaFin = ((JTextField) dchFin.getDateEditor().getUiComponent()).getText();

        JInternalFrameGraficarVentas interGraficarVenta = new JInternalFrameGraficarVentas();
        jDesktopPane_menu.add(interGraficarVenta);
        interGraficarVenta.setVisible(true);
    }//GEN-LAST:event_btnGraficarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private com.toedter.calendar.JDateChooser dchFin;
    private com.toedter.calendar.JDateChooser dchInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
